"""Initial migration

Revision ID: eb8a545512a8
Revises: 
Create Date: 2025-07-02 16:31:33.744616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8a545512a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('pfp', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Threads',
    sa.Column('threadID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('creatorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('threadID')
    )
    op.create_table('Posts',
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('threadID', sa.Integer(), nullable=True),
    sa.Column('creatorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creatorID'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['threadID'], ['Threads.threadID'], ),
    sa.PrimaryKeyConstraint('postID')
    )
    op.create_table('Comments',
    sa.Column('commentID', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('threadID', sa.Integer(), nullable=False),
    sa.Column('postID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postID'], ['Posts.postID'], ),
    sa.ForeignKeyConstraint(['threadID'], ['Threads.threadID'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('commentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comments')
    op.drop_table('Posts')
    op.drop_table('Threads')
    op.drop_table('Users')
    # ### end Alembic commands ###
